### ISSUE TITLE
How to cite your dataset VV

### ISSUE THREAD

**Issue by lilubit** [bbonik/image_enhancement#1]
Hi, thanks for your work and I would like to know how to cite your dataset VV.

**Comment by ghost** [comment]
Unfortunately, this dataset has not been introduced with any paper. Perhaps you can cite [this webpage](https://sites.google.com/site/vonikakis/datasets/tm-died?authuser=0)

**Comment by lilubit** [comment]
> Unfortunately, this dataset has not been introduced with any paper. Perhaps you can cite [this webpage](https://sites.google.com/site/vonikakis/datasets/tm-died?authuser=0)
Ok, thanks for your reply.
